#!/usr/bin/env bash
# Mission Control — installer.
#
#   sudo ./scripts/install.sh [--dry-run] [--hermes-home PATH]
#
# Does every mechanical step: service user, secrets file with generated
# passwords, virtualenv, templated systemd units, tailscale operator
# access, database, migrations. Idempotent — safe to re-run after a
# `git pull`, and it never regenerates secrets that already exist.
#
# It deliberately does NOT do the four steps that are yours:
#   1. enable HTTPS certificates in the tailnet admin console
#   2. replace the tailnet's default ACL with deploy/tailscale/acl-snippet.hujson
#   3. mint an OpenClaw gateway token and arm its exec policy
#   4. pair Mission Control as an approval reviewer device
# It prints them at the end.
set -euo pipefail

DRY=0
HERMES_HOME_ARG=""
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY=1 ;;
    --hermes-home) HERMES_HOME_ARG="$2"; shift ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

REPO="$(cd "$(dirname "$0")/.." && pwd)"
ENV_DIR=/etc/mission-control
ENV_FILE="$ENV_DIR/env"
SERVICE_USER=missionctl

step() { printf '\n\033[1m» %s\033[0m\n' "$1"; }
info() { printf '  %s\n' "$1"; }
run() {
  if [ "$DRY" = 1 ]; then printf '  \033[2m[dry-run] %s\033[0m\n' "$*"
  else "$@"; fi
}

[ "$DRY" = 1 ] || [ "$(id -u)" = 0 ] || { echo "run as root (or pass --dry-run)" >&2; exit 1; }

step "Service user"
if id "$SERVICE_USER" >/dev/null 2>&1; then
  info "$SERVICE_USER already exists"
else
  run useradd --system --home-dir "$REPO" --shell /usr/sbin/nologin "$SERVICE_USER"
  [ "$DRY" = 1 ] || info "created $SERVICE_USER (system account, no shell)"
fi

step "Secrets at $ENV_FILE"
if [ -f "$ENV_FILE" ]; then
  info "already present — leaving it untouched (no secret is ever regenerated)"
else
  run mkdir -p "$ENV_DIR"
  if [ "$DRY" = 1 ]; then
    info "[dry-run] would generate 4 passwords and write $ENV_FILE"
  else
    gen() { openssl rand -hex 24; }
    SUPER=$(gen); MIG=$(gen); APP=$(gen); RO=$(gen)
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Secrets live here and never in the repo (§12 S5).
#
# QUOTE EVERY VALUE. systemd's EnvironmentFile takes the whole line, but
# this file is also sourced by shell (`set -a; . /etc/mission-control/env`)
# in the helper scripts and the runbooks. There, an unquoted value
# containing a space is silently truncated at the space AND the remainder
# is executed as a command. An emptied MC_WORKSPACE_ALLOWLIST is fail-safe
# — everything then grades critical — but you would spend an afternoon
# working out why.

MC_DB_SUPERUSER_PASSWORD="$SUPER"
MC_DB_MIGRATE_PASSWORD="$MIG"
MC_DB_APP_PASSWORD="$APP"
MC_DB_READONLY_PASSWORD="$RO"

MC_BIND_HOST="127.0.0.1"
MC_BIND_PORT="8100"
MC_DATABASE_URL="postgresql+psycopg://mc_app:$APP@127.0.0.1:5432/mission_control"
MC_MIGRATE_DATABASE_URL="postgresql+psycopg://mc_migrate:$MIG@127.0.0.1:5432/mission_control"

MC_TAILSCALE_BIN="tailscale"
MC_OPERATOR_PEER_UIDS="0"
MC_REQUIRE_PEER_UID="true"

MC_LOG_LEVEL="INFO"

# ── adapters — fill these in, then restart mission-control-api ──
MC_OPENCLAW_URL="ws://127.0.0.1:18789"
MC_OPENCLAW_TOKEN=""
MC_HERMES_HOME="${HERMES_HOME_ARG}"
MC_HERMES_EXPECTED_SCHEMA_VERSION="26"

# Writes outside these roots are classified critical and can never be
# auto-approved. Empty means nothing can be proven contained, so every
# path write asks — safe, but noisy.
MC_WORKSPACE_ALLOWLIST=""
EOF
    chown root:"$SERVICE_USER" "$ENV_FILE"
    chmod 0640 "$ENV_FILE"
    info "wrote $ENV_FILE (root:$SERVICE_USER 0640) with generated passwords"
  fi
fi

step "Python environment"
if [ -x "$REPO/api/.venv/bin/python" ]; then
  info "virtualenv exists; updating dependencies"
else
  run python3.12 -m venv "$REPO/api/.venv"
fi
run "$REPO/api/.venv/bin/pip" install --quiet --upgrade pip
run "$REPO/api/.venv/bin/pip" install --quiet -e "$REPO/api"
run chown -R "$SERVICE_USER:$SERVICE_USER" "$REPO/api/.venv"

step "Tailscale operator access"
info "the API shells out to 'tailscale whois' to verify operator identity"
if command -v tailscale >/dev/null 2>&1; then
  run tailscale set --operator="$SERVICE_USER"
else
  info "tailscale not installed — skipping (identity verification will fail closed)"
fi

step "systemd units"
HERMES_HOME_VALUE="$HERMES_HOME_ARG"
if [ -z "$HERMES_HOME_VALUE" ] && [ -f "$ENV_FILE" ]; then
  HERMES_HOME_VALUE=$(sed -n 's/^MC_HERMES_HOME=//p' "$ENV_FILE" | head -1)
fi
for unit in mission-control-db mission-control-migrate mission-control-api; do
  src="$REPO/deploy/systemd/$unit.service"
  if [ "$DRY" = 1 ]; then
    info "[dry-run] would install $unit.service"
    continue
  fi
  tmp=$(mktemp)
  sed -e "s|/opt/mission-control|$REPO|g" "$src" > "$tmp"
  if [ "$unit" = "mission-control-api" ]; then
    if [ -n "$HERMES_HOME_VALUE" ]; then
      # ProtectHome=yes hides /home, so the Hermes state must be bound back
      # in READ-ONLY — which also enforces §6.2's never-write rule at the
      # OS level rather than by code discipline alone.
      sed -i "s|^BindReadOnlyPaths=.*|BindReadOnlyPaths=-$HERMES_HOME_VALUE|" "$tmp"
      info "bound $HERMES_HOME_VALUE read-only into the API sandbox"
    else
      sed -i "/^BindReadOnlyPaths=/d" "$tmp"
      info "no Hermes home configured — omitted the bind mount"
    fi
  fi
  install -m 0644 "$tmp" "/etc/systemd/system/$unit.service"
  rm -f "$tmp"
  info "installed $unit.service"
done
run systemctl daemon-reload

step "Database and schema"
run systemctl enable --now mission-control-db
run systemctl enable --now mission-control-migrate
if [ "$DRY" = 0 ]; then
  head=$(cd "$REPO/api" && set -a && . "$ENV_FILE" && set +a && \
    ./.venv/bin/alembic current 2>/dev/null | tail -1)
  info "migration head: ${head:-unknown}"
fi

step "Web app"
if command -v npm >/dev/null 2>&1; then
  run bash -c "cd '$REPO/web' && npm ci --silent && npm run build --silent"
  [ "$DRY" = 1 ] || info "built web/out"
else
  info "npm not present — the API will serve the Phase 0 hello page and /v1/*"
  info "build web/ elsewhere and copy the 'out' directory here"
fi

step "API service"
run systemctl enable --now mission-control-api
if [ "$DRY" = 0 ]; then
  sleep 2
  if curl -fsS --max-time 5 http://127.0.0.1:8100/health >/dev/null 2>&1; then
    info "health endpoint responding on 127.0.0.1:8100"
  else
    info "health endpoint NOT responding — journalctl -u mission-control-api -n 40"
  fi
fi

if [ "$DRY" = 1 ]; then
  printf '\n\033[2mDry run — nothing was changed. Re-run without --dry-run to apply.\033[0m\n\n'
  exit 0
fi

cat <<'NEXT'

──────────────────────────────────────────────────────────────────────
Installed. Four steps remain, and each one is yours:

  1. Tailnet admin console → DNS → enable HTTPS certificates.
     Serve cannot get a TLS certificate without it, and no HTTPS means
     no PWA later.

  2. Merge deploy/tailscale/acl-snippet.hujson into the tailnet policy,
     replacing the default allow-all rule. Layer 2 of the trust model
     does not exist until that default rule is gone.

  3. Start Serve, then arm the OpenClaw gate:
       sudo MC_BIND_PORT=8100 ./deploy/tailscale/serve-setup.sh
       openclaw exec-policy set --ask-fallback deny
     Put a gateway token in MC_OPENCLAW_TOKEN and set MC_HERMES_HOME,
     then: sudo systemctl restart mission-control-api

  4. Pair Mission Control as an OpenClaw approval reviewer device and
     add its id to approvalReviewerDeviceIds — without this the queue
     stays empty and looks idle. docs/phase-2-runbook.md §4c has the
     liveness drill that proves it works.

Then verify:
     ./scripts/preflight.sh          # should be all green now
     ./scripts/verify-phase2.sh      # end-to-end over real HTTP
──────────────────────────────────────────────────────────────────────
NEXT
